print ("hello world")
print ("Git is cool")
print("This is feature branch")
print ("Change on master")
print("Another feature")
print("Master change after rebase branch")
print("Change made on GitHub feature")
